### ISSUE TITLE
打包个docker可以吗

### ISSUE THREAD

**Issue by 2328760190** [kkkunny/ChandlerAiAPI#1]

**Comment by kkkunny** [comment]
项目目录下有Dockerfile文件，直接自己构建即可
`docker build -t ChandlerAiAPI:latest .`
`docker run -d --name ChandlerAi -p 5694:80 ChandlerAiAPI:latest`

**Comment by 2328760190** [comment]
谢谢你

在 2024-10-25 19:14:49，kkkunny ***@***.***> 写道：


项目目录下有Dockerfile文件，直接自己构建即可
docker build -t ChandlerAiAPI:latest .
docker run -d --name ChandlerAi -p 5694:80 ChandlerAiAPI:latest
